services:
  embedding-service:
    build: ./embedding-service
    ports:
      - "9000:8001"
    volumes:
      - K:/sentence_transformers/paraphrase-multilingual-MiniLM-L12-v2:/models
    environment:
      MODEL_PATH: /models

  backend:
    build: ./backend-chatbot
    ports:
      - "3000:3000"
    depends_on:
      - embedding-service
      - db

  db:
    image: 
    environment:
      POSTGRES_PASSWORD:
    ports:
      - ""
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d